---
title: "Shoulder-but-not-tail inflation"
author: "Lei Sun"
date: "2018-12-12"
output:
  workflowr::wflow_html:
    code_folding: hide
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r}
## read in data
z <- readRDS("../data/z.sel.rds")[3, ]
p <- pnorm(-abs(z)) * 2
```

```{r}
## histogram of correlated null z-scores

# setEPS()
# postscript("../figures/hist_cor_z.eps", width = 6.5, height = 5)
pdf("../figures/hist_cor_z.pdf", width = 6.5, height = 5)

par(mar = c(4.5, 4.5, 2.5, 1))

hist(z, breaks = seq(-10, 10, by = 0.1), prob = TRUE, ylim = c(0, dnorm(0)), xlab = "z-score", xlim = range(c(abs(z), -abs(z))), main = expression("(a): Histogram of correlated z-scores"), cex.main = 2, cex.lab = 2)

x.plot = seq(- max(abs(z)) - 2, max(abs(z)) + 2, length = 1000)
lines(x.plot, dnorm(x.plot), col = "blue", lwd = 3)

legend("topright", expression('N(0,1)'), lty = 1, col = 'blue', lwd = 3, cex = 1.75, bty = 'n', seg.len = 1.5, x.intersp = 0.5)
```

```{r}
## histogram of correlated null p-values

# setEPS()
# postscript("../figures/hist_cor_pval.eps", width = 6.5, height = 5)
pdf("../figures/hist_cor_pval.pdf", width = 6.5, height = 5)

par(mar = c(4.5, 4.5, 2.5, 1))

hist(p, prob = TRUE, breaks = seq(0, 1, by = 0.01), xlab = "p-value", main = expression("(b): Histogram of correlated p-values"), cex.main = 2, cex.lab = 2)

segments(x0 = 0, x1 = 1, y0 = 1, y1 = 1, col = "blue", lwd = 3)

legend("topright", expression('Uniform[0,1]'), lty = 1, col = 'blue', lwd = 3, cex = 1.75, bty = 'n', seg.len = 1.5, x.intersp = 0.5)
```

```{r}
## empirical CDF of correlated z-scores

# setEPS()
# postscript("../figures/ecdf_cor_z.eps", width = 5, height = 5)
pdf("../figures/ecdf_cor_z.pdf", width = 5, height = 5)

par(mar = c(4.5, 4.5, 2.5, 1))

plot(ecdf(z), xlab = "z-score", ylab = "CDF", lwd = 2, main = expression("(c): Empirical CDF"), cex.main = 2, cex.lab = 2, xlim = c(-max(abs(z)), max(abs(z))))
lines(seq(-6, 6, by = 0.01), pnorm(seq(-6, 6, by = 0.01)), col = "blue", lwd = 3, lty = 2)
lines(seq(-6, 6, by = 0.01), pnorm(seq(-6, 6, by = 0.01), 0, 1.6), col = "green", lwd = 3, lty = 4)
rect(xleft = c(-5, 2.5),
     xright = c(-2.5, 5),
     ytop = c(0.05, 1),
     ybottom = c(0, 0.95), border = "red", lty = c(1, 5))
legend("topleft", c("Correlated z-scores", expression(N(0,1)), expression(N(0, 1.6^2))), lty = c(1, 2, 4), col = c("black", "blue", "green"), lwd = 3, cex = 1.25, bty = 'n', seg.len = 1.5, x.intersp = 0.5)
```

```{r}
## empirical CDF of correlated z-scores: left tail

# setEPS()
# postscript("../figures/ecdf_cor_z_left.eps", width = 5, height = 5)
pdf("../figures/ecdf_cor_z_left.pdf", width = 5, height = 5)

par(mar = c(4.5, 4.5, 2.5, 1))

plot(ecdf(z), xlab = "z-score", ylab = "CDF", main = expression("(d): Left Tail of CDF"), lwd = 3, xlim = c(-5, -2.5), ylim = c(0, 0.05), cex.main = 2, cex.lab = 2, bty = "n")
box(col = "red")
lines(seq(-6, 6, by = 0.01), pnorm(seq(-6, 6, by = 0.01)), col = "blue", lwd = 3, lty = 2)
lines(seq(-6, 6, by = 0.01), pnorm(seq(-6, 6, by = 0.01), 0, 1.6), col = "green", lwd = 3, lty = 4)

legend("topleft", c("Correlated z-scores", expression(N(0,1)), expression(N(0, 1.6^2))), lty = c(1, 2, 4), col = c("black", "blue", "green"), lwd = 3, cex = 1.25, bty = 'n', seg.len = 1.5, x.intersp = 0.5)
```

```{r}
## empirical CDF of correlated z-scores: right tail

# setEPS()
# postscript("../figures/ecdf_cor_z_right.eps", width = 5, height = 5)
pdf("../figures/ecdf_cor_z_right.pdf", width = 5, height = 5)

par(mar = c(4.5, 4.5, 2.5, 1))

plot(ecdf(z), xlab = "z-score", ylab = "CDF", main = expression("(e): Right Tail of CDF"), lwd = 3, xlim = c(2.5, 5), ylim = c(0.95, 1), cex.main = 2, cex.lab = 2, bty = "n")
box(col = "red", lty = 5)
lines(seq(-6, 6, by = 0.01), pnorm(seq(-6, 6, by = 0.01)), col = "blue", lwd = 3, lty = 2)
lines(seq(-6, 6, by = 0.01), pnorm(seq(-6, 6, by = 0.01), 0, 1.6), col = "green", lwd = 3, lty = 4)

legend("bottomright", c("Correlated z-scores", expression(N(0,1)), expression(N(0, 1.6^2))), lty = c(1, 2, 4), col = c("black", "blue", "green"), lwd = 3, cex = 1.25, bty = 'n', seg.len = 1.5, x.intersp = 0.5)
```

```{r}
thresh.color <- c("maroon", "purple", "orange")

## generate iid samples from N(0,1) and N(0,1.6^2)
set.seed(777)
p.norm.1.6 <- pnorm(-abs(rnorm(1e4, 0, 1.6))) * 2
set.seed(77)
p.norm.1 <- pnorm(-abs(rnorm(1e4))) * 2
y.max <- -log(min(p.norm.1, p, p.norm.1.6))
y.max <- 20
```


```{r}
## log(p-values) of correlated null z-scores

# setEPS()
# postscript("../figures/logpval_cor_null.eps", width = 5, height = 5)
# pdf("../figures/logpval_cor_null.pdf", width = 5, height = 5)
png("../figures/logpval_cor_null.png", width = 5, height = 5, units = "in", res = 1000)

par(mar = c(4.5, 4.5, 2.5, 1))

set.seed(777)
plot(sample(-log(p)), ylim = c(0, y.max), ylab = "-log(p-value)", main = expression('(f): Correlated z-scores'), cex.main = 2, cex.lab = 2, pch = 19)
abline(h = -log(c(
  0.005,
  pnorm(-sqrt(2 * log(1e4))) * 2,
  0.05 / 1e4
)), lwd = 3, col = thresh.color, lty = c(1, 2, 4))
```

```{r}
## log(p-values) of iid null z-scores

# setEPS()
# postscript("../figures/logpval_iid_null.eps", width = 5, height = 5)
# pdf("../figures/logpval_iid_null.pdf", width = 5, height = 5)
png("../figures/logpval_iid_null.png", width = 5, height = 5, units = "in", res = 1000)

par(mar = c(4.5, 4.5, 2.5, 1))

plot(-log(p.norm.1), ylim = c(0, y.max), ylab = "-log(p-value)", main = expression("(g): iid N(0,1) z-scores"), col = "blue", cex.main = 2, cex.lab = 2, pch = 19)
abline(h = -log(c(
  0.005,
  pnorm(-sqrt(2 * log(1e4))) * 2,
  0.05 / 1e4
)), lwd = 3, col = thresh.color, lty = c(1, 2, 4))

legend("top",
       legend = c(
         latex2exp::TeX('p-value$= 0.05 / 10^4$'),
         'Univsal Threshold',
         latex2exp::TeX('p-value$= 0.005')
         ), lty = c(4, 2, 1), lwd = 3, xpd = NA,
       col = thresh.color[3 : 1], ncol = 1, bty = 'n', cex = 1.25)
```

```{r}
## log(p-values) of iid null z-scores

# setEPS()
# postscript("../figures/logpval_iid_N016.eps", width = 5, height = 5)
# pdf("../figures/logpval_iid_N016.pdf", width = 5, height = 5)
png("../figures/logpval_iid_N016.png", width = 5, height = 5, units = "in", res = 1000)

par(mar = c(4.5, 4.5, 2.5, 1))

plot(-log(p.norm.1.6), ylim = c(0, y.max), ylab = "-log(p-value)", main = expression(paste("(h): iid ", N(0, 1.6^2), " z-scores")), col = "green", cex.main = 2, cex.lab = 2, pch = 19)
abline(h = -log(c(
  0.005,
  pnorm(-sqrt(2 * log(1e4))) * 2,
  0.05 / 1e4
)), lwd = 3, col = thresh.color, lty = c(1, 2, 4))

# legend("topright", inset = c(-0.52, 0.3),
#        legend = c(
#          latex2exp::TeX('$p = 0.05 / 10^4$'),
#          'Univ Thresh',
#          "p = 0.005"
#          ), lty = c(4, 2, 1), lwd = 3, xpd = NA,
#        col = thresh.color[3 : 1], ncol = 1, cex = 1.5, bty = "n", x.intersp = 0.5, seg.len = 1.5)
```
