---
title: "Standardized Gaussian Derivatives"
author: "Lei Sun"
date: "2018-12-12"
output:
  workflowr::wflow_html:
    code_folding: hide
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r}
## calculate the values of standardized Gaussian derivatives at a number of plotting positions
x.plot <- seq(-10, 10, length = 1000)
gd.ord <- 10
x.plot.st.gd.mat <- cashr::std.gaussDeriv(x.plot, gd.ord)
method.col <- scales::hue_pal()(gd.ord)
```

```{r}
# setEPS()
# postscript("../figures/stdGD.eps", height = 4.5, width = 15)
pdf("../figures/stdGD.pdf", height = 4.5, width = 15)

par(mfrow = c(1, 2))
par(mar = c(3, 6.5, 1, 1.5))

plot(x.plot, dnorm(x.plot), type = "l", xlim = c(-5, 5), ylim = range(x.plot.st.gd.mat), xlab = "", ylab = '', main = '', bty = 'n', lwd = 2)
title(ylab = latex2exp::TeX('$\\frac{1}{\\sqrt{\\textit{l}!}}\\varphi^{(\\textit{l})}(\\cdot)$'), line = 2.5, cex.lab = 1.5)
for (i in 1 : 4) {
  lines(x.plot, x.plot.st.gd.mat[, (i + 1)], col = method.col[i], lty = i + 1, lwd = 2)
}
legend("topright", col = c(1, method.col[1 : 4]), lty = 1 : 5, lwd = 2, bty = "n", cex = 1.5,
       c(latex2exp::TeX('$\\varphi$'), 
         latex2exp::TeX('$\\textit{l} = 1$'), 
         latex2exp::TeX('$\\textit{l} = 2$'), 
         latex2exp::TeX('$\\textit{l} = 3$'), 
         latex2exp::TeX('$\\textit{l} = 4$')
       ))

plot(x.plot, dnorm(x.plot), type = "l", xlim = c(-5, 5), ylim = range(x.plot.st.gd.mat), xlab = "", ylab = '', main = '', bty = 'n', lwd = 2)
title(ylab = latex2exp::TeX('$\\frac{1}{\\sqrt{\\textit{l}!}}\\varphi^{(\\textit{l})}(\\cdot)$'), line = 2.5, cex.lab = 1.5)
for (i in 7 : 10) {
  lines(x.plot, x.plot.st.gd.mat[, (i + 1)], col = method.col[i], lty = i + 1, lwd = 2)
}
legend("topright", col = c(1, method.col[7 : 10]), lty = c(1, 8 : 11), lwd = 2, bty = "n", cex = 1.5,
       c(latex2exp::TeX('$\\varphi$'), 
         latex2exp::TeX('$\\textit{l} = 7$'), 
         latex2exp::TeX('$\\textit{l} = 8$'), 
         latex2exp::TeX('$\\textit{l} = 9$'), 
         latex2exp::TeX('$\\textit{l} = 10$')
       ))
```
