---
title: "Analyze the leukemia and mouse heart data"
author: "Lei Sun"
date: "2018-12-12"
output:
  workflowr::wflow_html:
    code_folding: hide
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

## Common settings for both data sets

```{r}
## set colors for `locfdr` and `cashr`
method.col <- scales::hue_pal()(5)

## calculate the values of standardized Gaussian derivatives as basis functions at a number of plotting positions
x.plot <- seq(-10, 10, length = 1000)
gd.ord <- 10
x.plot.st.gd.mat <- cashr::std.gaussDeriv(x.plot, gd.ord)

## ylim for both histograms
y.lim <- c(0, 0.235)

## nominal FDR
q <- 0.1
```

## Leukemia data

```{r}
## read in data
load(url("http://statweb.stanford.edu/~ckirby/brad/LSI/datasets-and-programs/data/leukdata.RData"))
```

```{r}
## obtain summary statistics using Smyth's pipeline
design <- model.matrix(~colnames(leukdata))
lim = limma::lmFit(leukdata, design)
r.ebayes = limma::eBayes(lim)
p = r.ebayes$p.value[, 2]
t = r.ebayes$t[, 2]
z = -sign(t) * qnorm(p/2)
X = lim$coefficients[, 2]
s = X / z
```

```{r}
## fitting `locfdr` and `cashr`
fit.locfdr <- locfdr::locfdr(z, plot = 0)
fit.cashr <- cashr::cash(X, s)
```

```{r}
## calculate fitted empirical null distribution from `locfdr`, scaled by fitted null proportion
y.plot.locfdr = dnorm(x.plot, fit.locfdr$fp0[3, 1], fit.locfdr$fp0[3, 2]) * fit.locfdr$fp0[3, 3]

## calculate fitted correlated noise distribution from `cashr`, scaled by fitted null proportion
y.plot.cashr = x.plot.st.gd.mat %*% fit.cashr$omega * fit.cashr$fitted_g$pi[1]
```

```{r}
# setEPS()
# postscript("../figures/leukemia_hist.eps", height = 5, width = 6)
pdf("../figures/leukemia_hist.pdf", height = 5, width = 6)

#####

hist(z, prob = TRUE, xlab = expression(paste(z, "-score")), cex.lab = 1.25, breaks = 50, main = expression("Leukemia data"), cex.main = 1.5, xlim = c(-10, 10), ylim = y.lim)

lines(x.plot, dnorm(x.plot), col = "orange", lty = 1, lwd = 2.5)
lines(x.plot, y.plot.locfdr, col = method.col[3], lty = 1, lwd = 2.5)
lines(x.plot, y.plot.cashr, col = method.col[5], lwd = 2.5)

text(-3.5, 0.188, "N(0,1)", col = "orange")
arrows(-2.2, 0.188, -1.3, 0.183, length = 0.1, angle = 20, col = "orange")

text(-6.3, 0.11, bquote(atop(" locfdr empirical null", .(round(fit.locfdr$fp0[3, 3], 2)) %*% N(.(round(fit.locfdr$fp0[3, 1], 2)), .(round(fit.locfdr$fp0[3, 2], 2))^2))), col = method.col[3])
arrows(-2.8, 0.1115, -1.9, 0.1065, length = 0.1, angle = 20, col = method.col[3])

text(4.4, 0.0925,
     bquote(atop("                     cashr corr noise dist", .(round(fit.cashr$fitted_g$pi[1], 2)) %*% hat(f))),
     col = method.col[5])
arrows(2.9, 0.10, 2, 0.095, length = 0.1, angle = 20, col = method.col[5])
```

```{r}
## number of discoveries at nominal FDR = 0.1
cashr.d <- sum(fit.cashr$qvalue <= q)

locfdr.d <- sum(ashr::qval.from.lfdr(fit.locfdr$fdr) <= q)

fit.BH <- p.adjust(p, method = "BH")
BH.d <- sum(fit.BH <= q)

fit.qvalue <- qvalue::qvalue(p)
qvalue.d <- sum(fit.qvalue$qvalues <= q)

fit.ashr <- ashr::ash(X, s, mixcompdist = "normal", method = "fdr")
ashr.d <- sum(ashr::get_qvalue(fit.ashr) <= q)

leuk.d <- c(
  cashr.d,
  locfdr.d,
  BH.d,
  qvalue.d,
  ashr.d
)
```

## Mouse heart data

```{r}
## read in data
mouse <- read.table("../data/smemo.txt", header = T, row.name = 1)
mouse = mouse[, -5]
## filter out lowly expressed genes
mouse = mouse[rowSums(mouse) >= 5, ]
```

```{r}
## obtain summary statistics using Smyth's pipeline
design = model.matrix(~substr(colnames(mouse), 1, 2))
dgecounts = edgeR::calcNormFactors(edgeR::DGEList(counts = mouse, group = design[, 2]))
v = limma::voom(dgecounts, design, plot = FALSE)
lim = limma::lmFit(v)
r.ebayes = limma::eBayes(lim)
p = r.ebayes$p.value[, 2]
t = r.ebayes$t[, 2]
z = -sign(t) * qnorm(p/2)
X = lim$coefficients[, 2]
s = X / z
```

```{r}
## fitting `locfdr` and `cashr`
fit.locfdr <- locfdr::locfdr(z, plot = 0)
fit.cashr <- cashr::cash(X, s)
```

```{r}
## calculate fitted empirical null distribution from `locfdr`, scaled by fitted null proportion
y.plot.locfdr = dnorm(x.plot, fit.locfdr$fp0[3, 1], fit.locfdr$fp0[3, 2]) * fit.locfdr$fp0[3, 3]

## calculate fitted correlated noise distribution from `cashr`, scaled by fitted null proportion
y.plot.cashr = x.plot.st.gd.mat %*% fit.cashr$omega * fit.cashr$fitted_g$pi[1]
```

```{r}
# setEPS()
# postscript("../figures/mouse_hist.eps", height = 5, width = 6)
pdf("../figures/mouse_hist.pdf", height = 5, width = 6)

hist(z, prob = TRUE, main = expression("Mouse data"), xlab = expression(paste(z, "-score")), cex.lab = 1.25, xlim = c(-10, 10), ylim = y.lim, cex.main = 1.5)

lines(x.plot, dnorm(x.plot), col = "orange", lty = 1, lwd = 2.5)
lines(x.plot, y.plot.cashr, col = method.col[5], lwd = 2.5)
lines(x.plot, y.plot.locfdr, col = method.col[3], lty = 1, lwd = 2.5)

text(-3.5, 0.188, "N(0,1)", col = "orange")
arrows(-2.2, 0.188, -1.3, 0.183, length = 0.1, angle = 20, col = "orange")

text(-6.8, 0.11, bquote(atop(" locfdr empirical null", .(round(fit.locfdr$fp0[3, 3], 2)) %*% N(.(round(fit.locfdr$fp0[3, 1], 2)), .(round(fit.locfdr$fp0[3, 2], 2))^2))), col = method.col[3])
arrows(-3.3, 0.1115, -2.4, 0.1065, length = 0.1, angle = 20, col = method.col[3])

text(5.1, 0.090,
     bquote(atop("                    cashr corr noise dist", .(round(fit.cashr$fitted_g$pi[1], 2)) %*% hat(f))),
     col = method.col[5])
arrows(3.5, 0.0975, 2.6, 0.0925, length = 0.1, angle = 20, col = method.col[5])
```

## Numbers of discoveries at nominal FDR = 0.1

```{r}
## number of discoveries at nominal FDR = 0.1
cashr.d <- sum(fit.cashr$qvalue <= q)

locfdr.d <- sum(ashr::qval.from.lfdr(fit.locfdr$fdr) <= q)

fit.BH <- p.adjust(p, method = "BH")
BH.d <- sum(fit.BH <= q)

fit.qvalue <- qvalue::qvalue(p)
qvalue.d <- sum(fit.qvalue$qvalues <= q)

fit.ashr <- ashr::ash(X, s, mixcompdist = "normal", method = "fdr")
ashr.d <- sum(ashr::get_qvalue(fit.ashr) <= q)

mouse.d <- c(
  cashr.d,
  locfdr.d,
  BH.d,
  qvalue.d,
  ashr.d
)
```

```{r}
table.d <- cbind.data.frame(
  Method = c(
    'cashr',
    'locfdr',
    'BH',
    'qvalue',
    'ashr'
  ),
  Leukemia = leuk.d,
  Mouse = mouse.d
)

knitr::kable(table.d)
```
