---
title: "Histograms of correlated $N(0,1)$"
author: "Lei Sun"
date: "2018-12-11"
output:
  workflowr::wflow_html:
    code_folding: hide
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r}
## read in data
z.sel <- readRDS("../data/z.sel.rds")
```

```{r}
## calculate the values of standardized Gaussian derivatives as basis functions at a number of plotting positions
gd.ord <- 10
x.plot = seq(- max(abs(z.sel)) - 2, max(abs(z.sel)) + 2, length = 1000)
x.plot.st.gd.mat <- cashr::std.gaussDeriv(x.plot, gd.ord)
```

```{r}
## calculate the range of x and y axes
x.lim <- range(c(abs(z.sel), -abs(z.sel)))
y.max <- max(hist(z.sel[4, ], breaks = 100, plot = FALSE)$density)
```

```{r}
## plotting

# setEPS()
# postscript("../figures/cor_N01_hist.eps", width = 8, height = 6)
pdf("../figures/cor_N01_hist.pdf", width = 8, height = 6)

par(mfrow = c(2, 2)) # 2-by-2 grid of plots
par(oma = c(0.5, 2.5, 0, 0)) # make room (i.e. the 4's) for the overall x and y axis titles
par(mar = c(2, 2, 3.5, 1)) # make the plots be closer together

# now plot the graphs with the appropriate axes removed (via xaxt and yaxt),
# remove axis labels (so that they are not redundant with overall labels,
# and set some other nice choices for graphics parameters
for (i in 1 : 4) {
  z = z.sel[i, ]
  omega <- cashr::ecn(z, gd.ord)$omega
  y.plot = x.plot.st.gd.mat %*% omega
  hist(z, breaks = seq(-10, 10, by = 0.1), prob = TRUE, ylim = c(0, y.max), main = NULL, xlab = "", xlim = x.lim)
  lines(x.plot, dnorm(x.plot), col = "blue", lwd = 2)
  lines(x.plot, y.plot, col = 'red', lwd = 2)
  legend("topleft", bty = "n", paste0('(', letters[i], ')'), cex = 1.25)
}

# print the overall labels
mtext('Density', side = 2, outer = TRUE, line = 1)
mtext(latex2exp::TeX('Histograms of $10^4$ Correlated N(0,1) z-scores'), line = -2, outer = TRUE)

legend("topleft", inset = c(-0.65, -0.25), legend = c("N(0, 1)", "Gaussian Derivatives"), lty = 1, lwd = 2, xpd = NA, col = c("blue", 'red'), ncol = 2)
```
