---
title: "Code and data resources accompanying [Sun and Stephens (2018)][]"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
---

We provide data and code resources accompanying [Sun and Stephens (2018)][]. The following pages display `R` code used to generate the results and figures in the paper.

* [Figure 1: Histograms of correlated $N(0,1)$ null $z$-scores](cashr_paper_fig_corN01.html)
* [Figure 2: Deconvolution by EBNM methods with correlated and independent noise](cashr_paper_fig_deconv.html)
* [Figure 3: Should-but-not-tail property of correlation-induced inflation](cashr_paper_fig_shoulder.html)
* [Figure 4: Standardized Gaussian derivatives](cashr_paper_fig_stdGD.html)
* [Figure 5: Large-scale realistic simulation on multiple testing and FDR](cashr_paper_fig_FDPsim.html)
* [Figure 6: Simulation results tratified by patterns of correlation-induced distortion patterns](cashr_paper_fig_FDPsimNoise.html)
* [Figure 7 and Table 1: Analyzing leukemia and mouse data](cashr_paper_fig_leukmouse.html)
* [Figure A.1 and A.2: Evidence to show the realistically simulated null $z$-scores are indeed margianlly $N(0,1)$](cashr_paper_fig_ecdf.html)

[Sun and Stephens (2018)]: https://arxiv.org/abs/1812.07488
